In [3]:
import pandas as pd

In [4]:
file_path = '../../Data/Raw/'

In [41]:
store_info= pd.read_csv(file_path +'store_details.csv' )
hist_info= pd.read_csv(file_path +'historical_information.csv' )

C:\Users\DEATHX7\AppData\Local\Temp\ipykernel_31148\1255787465.py:2: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  hist_info= pd.read_csv(file_path +'historical_information.csv' )

<h2>Store Dataset</h2>

<h3>1.Understanding Structure</h3>

In [ ]:
store_info.shape

(1115, 10)

In [ ]:
store_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1115 entries, 0 to 1114
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Store                      1115 non-null   int64
 1   StoreType                  1115 non-null   object
 2   Assortment                 1115 non-null   object
 3   CompetitionDistance        1112 non-null   float64
 4   CompetitionOpenSinceMonth  761 non-null    float64
 5   CompetitionOpenSinceYear   761 non-null    float64
 6   Promo2                     1115 non-null   int64
 7   Promo2SinceWeek            571 non-null    float64
 8   Promo2SinceYear            571 non-null    float64
 9   PromoInterval              571 non-null    object
dtypes: float64(5), int64(2), object(3)
memory usage: 87.2+ KB

In [71]:
store_info.CompetitionOpenSinceYear.isnull().sum()

np.int64(354)

In [ ]:
store_info.head(10)

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN
5,6,a,a,310.0,12.0,2013.0,0,NaN,NaN,NaN
6,7,a,c,24000.0,4.0,2013.0,0,NaN,NaN,NaN
7,8,a,a,7520.0,10.0,2014.0,0,NaN,NaN,NaN
8,9,a,c,2030.0,8.0,2000.0,0,NaN,NaN,NaN
9,10,a,a,3160.0,9.0,2009.0,0,NaN,NaN,NaN

<h3>2.Check missing values</h3>

In [ ]:
store_info.isnull().sum()

Store                          0
StoreType                      0
Assortment                     0
CompetitionDistance            3
CompetitionOpenSinceMonth    354
CompetitionOpenSinceYear     354
Promo2                         0
Promo2SinceWeek              544
Promo2SinceYear              544
PromoInterval                544
dtype: int64

In [ ]:
store_info.isnull().mean() *100

Store                         0.000000
StoreType                     0.000000
Assortment                    0.000000
CompetitionDistance           0.269058
CompetitionOpenSinceMonth    31.748879
CompetitionOpenSinceYear     31.748879
Promo2                        0.000000
Promo2SinceWeek              48.789238
Promo2SinceYear              48.789238
PromoInterval                48.789238
dtype: float64

<h3>You can do.</h3>

In [28]:
# CompetitionDistance            3

# Fill with median because distance are often skewed,
# More robust to outliers,
# Better for distance/location variavles
#_____________________________________________________________________
# CompetitionOpenSinceMonth    354
# CompetitionOpenSinceYear     354

# You can do this:
    # fill it to zero --> Refer to unknown/ no competition data.
    # Create feature like CompetitionOpen =1 if date exists else 0 
    #(Better both) 
#_____________________________________________________________________
# Promo2SinceWeek              544
# Promo2SinceYear              544
# PromoInterval                544

# For numerical columns just fill it with zero
# For Categorical/String fill it NoPromo (You can't fill it with zero to not break preprocessing/encoding )

<h3>3.Understanding Numerical columns</h3>

In [ ]:
store_info.describe()

,Store,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear
count,1115.00000,1112.000000,761.000000,761.000000,1115.000000,571.000000,571.000000
mean,558.00000,5404.901079,7.224704,2008.668857,0.512108,23.595447,2011.763573
std,322.01708,7663.174720,3.212348,6.195983,0.500078,14.141984,1.674935
min,1.00000,20.000000,1.000000,1900.000000,0.000000,1.000000,2009.000000
25%,279.50000,717.500000,4.000000,2006.000000,0.000000,13.000000,2011.000000
50%,558.00000,2325.000000,8.000000,2010.000000,1.000000,22.000000,2012.000000
75%,836.50000,6882.500000,10.000000,2013.000000,1.000000,37.000000,2013.000000
max,1115.00000,75860.000000,12.000000,2015.000000,1.000000,50.000000,2015.000000

In [ ]:
# CompetitionDistance is highly skewed
# CompetitionOpenSinceYear looks fine but Min= 1900???
# So did competitor really open in 1900? OR It just a default value (placeholder) OR Bad data

<h3>4.Exploring categorical columns</h3>

In [ ]:
store_info["StoreType"].value_counts()

StoreType
a    602
d    348
c    148
b     17
Name: count, dtype: int64

In [ ]:
store_info["Assortment"].value_counts()

Assortment
a    593
c    513
b      9
Name: count, dtype: int64

<h3>5.Check duplicates</h3>

In [13]:
store_info["Store"].nunique()

1115

In [14]:
store_info.duplicated().sum()

np.int64(0)

<h2>_______________________________________________________________________________________________</h2>

<h2>2.Historical information Dataset</h2>

<h3>1.Understanding strucure</h3>

In [25]:
hist_info.shape

(1017209, 9)

In [27]:
hist_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1017209 entries, 0 to 1017208
Data columns (total 9 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   Store          1017209 non-null  int64
 1   DayOfWeek      1017209 non-null  int64
 2   Date           1017209 non-null  object
 3   Sales          1017209 non-null  int64
 4   Customers      1017209 non-null  int64
 5   Open           1017209 non-null  int64
 6   Promo          1017209 non-null  int64
 7   StateHoliday   1017209 non-null  object
 8   SchoolHoliday  1017209 non-null  int64
dtypes: int64(7), object(2)
memory usage: 69.8+ MB

In [28]:
hist_info.head(10)

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,5,2015-07-31,5263,555,1,1,0,1
1,2,5,2015-07-31,6064,625,1,1,0,1
2,3,5,2015-07-31,8314,821,1,1,0,1
3,4,5,2015-07-31,13995,1498,1,1,0,1
4,5,5,2015-07-31,4822,559,1,1,0,1
5,6,5,2015-07-31,5651,589,1,1,0,1
6,7,5,2015-07-31,15344,1414,1,1,0,1
7,8,5,2015-07-31,8492,833,1,1,0,1
8,9,5,2015-07-31,8565,687,1,1,0,1
9,10,5,2015-07-31,7185,681,1,1,0,1

<h3>2.Check nulls & duplicates</h3>

In [66]:
hist_info.isnull().sum()

Store            0
DayOfWeek        0
Date             0
Sales            0
Customers        0
Open             0
Promo            0
StateHoliday     0
SchoolHoliday    0
dtype: int64

In [31]:
hist_info.duplicated().sum()

np.int64(0)

<h3>3.Exploring target variable (Sales)</h3>

In [35]:
hist_info["Sales"].describe()

count    1.017209e+06
mean     5.773819e+03
std      3.849926e+03
min      0.000000e+00
25%      3.727000e+03
50%      5.744000e+03
75%      7.856000e+03
max      4.155100e+04
Name: Sales, dtype: float64

In [38]:
(hist_info["Sales"] == 0).sum()

# Zero usually means closed

np.int64(172871)

<h3>4.Exploring Customers</h3>

In [36]:
hist_info["Customers"].describe()

count    1.017209e+06
mean     6.331459e+02
std      4.644117e+02
min      0.000000e+00
25%      4.050000e+02
50%      6.090000e+02
75%      8.370000e+02
max      7.388000e+03
Name: Customers, dtype: float64

In [39]:
# The relationship between Sales and customers
hist_info[["Sales", "Customers"]].corr()

              Sales  Customers
Sales      1.000000   0.894711
Customers  0.894711   1.000000

<h3>5.Exploring binary columns</h3>

In [43]:
hist_info["Open"].value_counts()

# Open zero = zero sales

Open
1    844392
0    172817
Name: count, dtype: int64

In [44]:
hist_info["Promo"].value_counts()

Promo
0    629129
1    388080
Name: count, dtype: int64

In [62]:
hist_info.groupby("SchoolHoliday")["Sales"].mean()
hist_info["SchoolHoliday"].value_counts()

SchoolHoliday
0    835488
1    181721
Name: count, dtype: int64

<h3>6.Explore categorical columns</h3>

In [46]:
hist_info["StateHoliday"].value_counts()

StateHoliday
0    855087
0    131072
a     20260
b      6690
c      4100
Name: count, dtype: int64

In [47]:
hist_info.groupby("StateHoliday")["Sales"].mean()

StateHoliday
0    5733.530624
0    5980.279717
a     290.735686
b     214.311510
c     168.733171
Name: Sales, dtype: float64

In [ ]:
# For categorical columns you need to set datatype to str 
# Because 0 is different of "0" and zero refer to non holiday

<h3>6.Explore DayOfWeek</h3>

In [48]:
hist_info["DayOfWeek"].value_counts()

DayOfWeek
5    145845
4    145845
3    145665
2    145664
1    144730
7    144730
6    144730
Name: count, dtype: int64

In [49]:
hist_info.groupby("DayOfWeek")["Sales"].mean()

DayOfWeek
1    7809.044510
2    7005.244467
3    6555.884138
4    6247.575913
5    6723.274305
6    5847.562599
7     204.183189
Name: Sales, dtype: float64

<h3>7.Explore Date column</h3>

In [50]:
hist_info["Date"].head()

0    2015-07-31
1    2015-07-31
2    2015-07-31
3    2015-07-31
4    2015-07-31
Name: Date, dtype: object

In [51]:
hist_info["Date"] = pd.to_datetime(hist_info["Date"])

In [58]:
# hist_info["Date"].min()
hist_info["Date"].max()

Timestamp('2015-07-31 00:00:00')