In [3]:
import pandas as pd

In [4]:
file_path = '../../Data/Raw/'

In [26]:
store_info= pd.read_csv(file_path +'store_details.csv' )
df2 = pd.read_csv(file_path +'historical_information.csv' )

C:\Users\DEATHX7\AppData\Local\Temp\ipykernel_13440\3157004154.py:2: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv(file_path +'historical_information.csv' )

<h3>1.Understanding Structure</h3>

In [ ]:
store_info.shape

(1115, 10)

In [ ]:
store_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1115 entries, 0 to 1114
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Store                      1115 non-null   int64
 1   StoreType                  1115 non-null   object
 2   Assortment                 1115 non-null   object
 3   CompetitionDistance        1112 non-null   float64
 4   CompetitionOpenSinceMonth  761 non-null    float64
 5   CompetitionOpenSinceYear   761 non-null    float64
 6   Promo2                     1115 non-null   int64
 7   Promo2SinceWeek            571 non-null    float64
 8   Promo2SinceYear            571 non-null    float64
 9   PromoInterval              571 non-null    object
dtypes: float64(5), int64(2), object(3)
memory usage: 87.2+ KB

In [ ]:
store_info.head(10)

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN
5,6,a,a,310.0,12.0,2013.0,0,NaN,NaN,NaN
6,7,a,c,24000.0,4.0,2013.0,0,NaN,NaN,NaN
7,8,a,a,7520.0,10.0,2014.0,0,NaN,NaN,NaN
8,9,a,c,2030.0,8.0,2000.0,0,NaN,NaN,NaN
9,10,a,a,3160.0,9.0,2009.0,0,NaN,NaN,NaN

<h3>2.Check missing values</h3>

In [ ]:
store_info.isnull().sum()

Store                          0
StoreType                      0
Assortment                     0
CompetitionDistance            3
CompetitionOpenSinceMonth    354
CompetitionOpenSinceYear     354
Promo2                         0
Promo2SinceWeek              544
Promo2SinceYear              544
PromoInterval                544
dtype: int64

In [ ]:
store_info.isnull().mean() *100

Store                         0.000000
StoreType                     0.000000
Assortment                    0.000000
CompetitionDistance           0.269058
CompetitionOpenSinceMonth    31.748879
CompetitionOpenSinceYear     31.748879
Promo2                        0.000000
Promo2SinceWeek              48.789238
Promo2SinceYear              48.789238
PromoInterval                48.789238
dtype: float64

<h3>You can do.</h3>

In [28]:
# CompetitionDistance            3

# Fill with median because distance are often skewed,
# More robust to outliers,
# Better for distance/location variavles
#_____________________________________________________________________
# CompetitionOpenSinceMonth    354
# CompetitionOpenSinceYear     354

# You can do this:
    # fill it to zero --> Refer to unknown/ no competition data.
    # Create feature like CompetitionOpen =1 if date exists else 0 
    #(Better both) 
#_____________________________________________________________________
# Promo2SinceWeek              544
# Promo2SinceYear              544
# PromoInterval                544

# For numerical columns just fill it with zero
# For Categorical/String fill it NoPromo (You can't fill it with zero to not break preprocessing/encoding )

<h3>3.Understanding Numerical columns</h3>

In [ ]:
store_info.describe()

,Store,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear
count,1115.00000,1112.000000,761.000000,761.000000,1115.000000,571.000000,571.000000
mean,558.00000,5404.901079,7.224704,2008.668857,0.512108,23.595447,2011.763573
std,322.01708,7663.174720,3.212348,6.195983,0.500078,14.141984,1.674935
min,1.00000,20.000000,1.000000,1900.000000,0.000000,1.000000,2009.000000
25%,279.50000,717.500000,4.000000,2006.000000,0.000000,13.000000,2011.000000
50%,558.00000,2325.000000,8.000000,2010.000000,1.000000,22.000000,2012.000000
75%,836.50000,6882.500000,10.000000,2013.000000,1.000000,37.000000,2013.000000
max,1115.00000,75860.000000,12.000000,2015.000000,1.000000,50.000000,2015.000000

In [ ]:
# CompetitionDistance is highly skewed
# CompetitionOpenSinceYear looks fine but Min= 1900???
# So did competitor really open in 1900? OR It just a default value (placeholder) OR Bad data

<h3>4.Exploring categorical columns</h3>

In [ ]:
store_info["StoreType"].value_counts()

StoreType
a    602
d    348
c    148
b     17
Name: count, dtype: int64

In [ ]:
store_info["Assortment"].value_counts()

Assortment
a    593
c    513
b      9
Name: count, dtype: int64